enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
included-patches = "'Alternative thumbnails' 'Always repeat' 'Announcements' 'Bypass URL redirects' 'Bypass image region restrictions' 'Change header' 'Check watch history domain name resolution' 'Copy video URL' 'Custom branding' 'Downloads' 'Hide Shorts components' 'Hide ads' 'Miniplayer' 'Open links externally' 'Playback speed' 'Remove background playback restrictions' 'Remove player controls background' 'Remove tracking query parameter' 'Remove viewer discretion dialog' 'Return YouTube Dislike' 'Seekbar thumbnails' 'Shorts autoplay' 'SponsorBlock' 'Spoof app version' 'Spoof video streams' 'Swipe controls' 'Theme' 'Video ads' 'Disable resuming Shorts on startup'"
build-mode = "both"
exclusive-patches = true
apkmirror-dpi = "nodpi"
arch = "arm64-v8a"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.br.uptodown.com/android"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dpi = "nodpi"
version = "auto"

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
uptodown-dlurl = "https://facebook.br.uptodown.com/android"
arch = "arm64-v8a"
apkmirror-dpi = "nodpi"
version = "auto"

[Instagram]
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.br.uptodown.com/android"
arch = "arm64-v8a"
apkmirror-dpi = "nodpi"
version = "auto"

[Photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath"
arch = "arm64-v8a"
version = "auto"

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.br.uptodown.com/android"
arch = "arm64-v8a"
apkmirror-dpi = "nodpi"
version = "auto"

[Lightroom]
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.br.uptodown.com/android"
arch = "arm64-v8a"
apkmirror-dpi = "nodpi"
version = "auto"
