enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
included-patches = "'Hide ads'"
exclusive-patches = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
arch = "arm64-v8a"

# [Tiktok]
# apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
# uptodown-dlurl = "https://tiktok.en.uptodown.com/android/"
# arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Disable auto captions' 'Hide player overlay buttons' 'Change form factor' 'Hide end screen cards' 'Hide end screen suggested video' 'Disable fullscreen ambient mode' 'Hide layout components' 'Hide info cards' 'Hide player flyout menu items' 'Hide related video overlay' 'Disable rolling number animations' 'Hide Shorts components' 'Hide timestamp' 'Wide search bar' 'Shorts autoplay' 'Open Shorts in regular player' 'Spoof app version' 'Change start page' 'Enable debugging' 'Disable haptic feedback' 'Force original audio' 'Disable HDR video'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/system_neutral1_900 -OlightThemeBackgroundColor=@android:color/system_neutral1_50 -e 'Custom branding' -OiconPath=ReVanced*Logo -OappName=YouTube"
